
url: "https://adilima-cersil.github.io"
baseurl: "/yuan"

title: Cersil Dinasti Yuan
author:
  name: FX. Adi Lima
  email: adi7598@gmail.com

description: >
  Membuat workflow sederhana untuk halaman web github, 
  hanya menggunakan W3CSS.

plugins:
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed
